---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  labels:
    app: kafka
  name: platform-mq
spec:
  kafka:
    config:
      auto.create.topics.enable: false
      log.retention.hours: 72
      num.recovery.threads.per.data.dir: 3
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1

    replicas: 1

    authorization:
      type: simple
      superUsers:
      - superuser
      - mirrormaker
      # because KafkaSource does not support SASL auth
      # only allowed from within the cluster
      - ANONYMOUS

    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: route
        tls: true
        authentication:
          type: scram-sha-512

    jvmOptions:
      -Xms: 2g
      -Xmx: 2g
    resources:
      limits:
        cpu: 200m
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 4Gi
    storage:
      deleteClaim: false
      size: 50Gi
      type: persistent-claim
    version: 2.7.0

  zookeeper:
    replicas: 1
    storage:
      deleteClaim: false
      size: 5Gi
      type: persistent-claim

  entityOperator:
    topicOperator: {}
    userOperator: {}

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: platform-mq
  name: mirrormaker
spec:
  authentication:
    type: scram-sha-512

