apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: notifications-knative-kafka

parameters:
- name: BOOTSTRAP_SERVERS
  value: platform-mq-kafka-bootstrap.kafka:9092

objects:
- apiVersion: sources.knative.dev/v1beta1
  kind: KafkaSource
  metadata:
    name: notifications-ingress-source
  spec:
    consumerGroup: knative
    bootstrapServers:
    - ${BOOTSTRAP_SERVERS}
    topics:
    - platform.notifications.ingress
    sink:
      ref:
        apiVersion: eventing.knative.dev/v1
        kind: Broker
        namespace: hrupp
        name: mybroker
